
<?php
require_once('vendor/autoload.php'); // Path to autoload.php generated by Composer

\Stripe\Stripe::setApiKey('sk_test_51OMAuuGzHFLuL4bhT7byH9AJcb6pxhVFl95LeU6APeXm6MP1x1Id4qt9nbFop7kDfvGmcPOg8LRJEBxWtiY16MGg002CdS0RNe');
?>

<!DOCTYPE html>
<html>
<head>
    <title>Stripe Donation</title>
    <meta charset="UTF-8" />
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            background-color: #f4f4f4;
        }

        .container {
            max-width: 400px;
            width: 100%;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        h1 {
            text-align: center;
        }

        form {
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        input[type="number"] {
            padding: 10px;
            width: 100%;
            margin-bottom: 15px;
            border-radius: 5px;
            border: 1px solid #ccc;
            box-sizing: border-box;
        }

        button {
            padding: 10px 20px;
            font-size: 16px;
            border: none;
            border-radius: 5px;
            background-color: #6495ED;
            color: white;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }

        button:hover {
            background-color: #6495ED;
        }
    </style>
</head>
<body>
	
    <div class="container">
		<button onclick="history.back()">Go Back</button>
        <h1>Stripe Donation</h1>
        <form method="post" action="checkout.php">
            <label for="amount">Enter Donation Amount (RM)</label>
            <input type="number" id="amount" name="amount" min="1" step="any" required>
            <button type="submit">Donate</button>
        </form>
    </div>
</body>
</html>
